# Generated by Django 5.2.11 on 2026-02-08 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("feed_url", models.URLField(max_length=1000, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "rss_feeds",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hn_id", models.IntegerField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("by", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                ("time", models.DateTimeField()),
                ("descendants", models.IntegerField(default=0)),
                ("type", models.CharField(default="story", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stories",
                "indexes": [
                    models.Index(fields=["hn_id"], name="stories_hn_id_0d2e57_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="RSSItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField(max_length=1000)),
                ("description", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.rssfeed"
                    ),
                ),
            ],
            options={
                "db_table": "rss_items",
                "unique_together": {("feed", "link")},
            },
        ),
    ]
