# Generated by Django 5.2.11 on 2026-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_default_feeds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rssitem",
            name="feed",
            field=models.CharField(max_length=500),
        ),
    ]
